title: 'lyyourc'
bio: 'Web Dev / Google-oriented Programming / zzz'
gh_username: 'lyyourc'

socials:
  - name: 'GitHub'
    link: 'https://github.com/lyyourc'
  - name: 'Weibo'
    link: 'http://weibo.com/cha12chalyc/'
  - name: 'Twitter'
    link: 'https://twitter.com/lyyourc'