title: 'lyyourc'
bio: 'Web 开发 / 面向 Google 编程 / 没特长'

socials:
  - name: 'GitHub'
    link: 'https://github.com/DrakeLeung'
  - name: 'Weibo'
    link: 'http://weibo.com/cha12chalyc/'
  - name: 'Twitter'
    link: 'https://twitter.com/DrakeLeung'