# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: left
widgets:
- category
- archive
- tagcloud

#- tag
#- recent_posts

# Miscellaneous
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

#### Analytics
google_analytics:
baidu_analytics: true

